insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Josh", "12", "cachorro", "SRD", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Luma", "35", "cachorro", "Golden Retrivier", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Rocha", "4", "gato", "SRD", true);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Polito", "6", "gato", "Sphynx", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Toby", "9", "Cachorro", "Shi-tzu", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("João", "23", "Cachorro", "SRD", true);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Juju", "6", "Cachorro", "SRD", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Tomás", "67", "Cachorro", "São Bernardo", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Norberto", "5", "Gato", "SRD", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Turbulenta", "3", "Gato", "SRD", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Gru", "15", "Cachorro", "Labrador", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Borboleta", "19", "Cachorro", "Labrador", false);
insert into tb_animais(nome, peso, tipo, raca, agressivo) values ("Boris", "4", "Gato", "SRD", true);